apiVersion: v1
kind: List
items:

- kind: ImageStream
  apiVersion: "v1"
  metadata:
    annotations:
      description: A service for periodically syncing a git repository
      tags: python, git
    name: 'git-sync'

- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "git-sync" 
  spec:
    
    runPolicy: "Serial" 
    
    triggers:
      - type: ConfigChange
      - github:
          secret: git-sync
        type: GitHub
    
    source: 
      git:
        uri: "https://github.com/vandayam/git-sync"
        ref: "master"
    
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
        forcePull: true
        
    output:
      to:
        kind: ImageStreamTag
        name: 'git-sync:latest'
